### ISSUE TITLE
mysql57 + log-bin causes update statement error

### ISSUE THREAD

**Issue by kitora** [mroonga/mroonga#130]
Prepare CentOS6.8 and  [mysql57-community-mroonga](http://mroonga.org/ja/docs/install/centos.html#centos-6-with-the-oracle-mysql-5-7-package).
I used centos:centos6.8 docker image.

Modify /etc/my.cnf to write binary logs
```
log-bin
server-id=1
```
Start mysqld service
```
service mysqld start
```
Start mysql and execute test code
```
-- mroonga_version 6.13
-- version 5.7.17-log
CREATE DATABASE error_test /*!40100 COLLATE 'utf8_general_ci' */;
USE error_test;
CREATE TABLE error_test (
	NAME VARCHAR(255) NOT NULL,
	VAL INT(11) NULL,
	PRIMARY KEY (NAME),
	INDEX IDX (VAL)
) COLLATE='utf8_general_ci' ENGINE=Mroonga;
INSERT INTO error_test VALUES ('mroonga.test',7);
INSERT INTO error_test VALUES ('mroooooongatest',10);
UPDATE error_test SET VAL=8 WHERE NAME = 'mroonga.test'; -- error
SELECT * FROM error_test WHERE NAME = 'mroonga.test' and VAL=8; -- but changed
UPDATE error_test SET VAL=10 WHERE NAME = 'mroooooongatest'; -- no error
```

On the first `UPDATE` statement returns error like 
```
mysql> UPDATE error_test SET VAL=8 WHERE NAME = 'mroonga.test'; -- error
ERROR 1265 (01000): data truncated for primary key column: <NAME>
```
But the data has been changed
```
mysql> SELECT * FROM error_test WHERE NAME = 'mroonga.test' and VAL=8; -- but changed
+--------------+------+
| NAME         | VAL  |
+--------------+------+
| mroonga.test |    8 |
+--------------+------+
1 row in set (0.00 sec)
```
On the second `UPDATE` statement which does not change the data returns no error
```
mysql> UPDATE error_test SET VAL=10 WHERE NAME = 'mroooooongatest'; -- no error
Query OK, 0 rows affected (0.00 sec)
Rows matched: 1  Changed: 0  Warnings: 0
```

Same error occurs , mysql56-mroonga + `binlog_format=ROW` mode.
It seems default value of binlog_format is ROW on mysql57.

**Comment by kou** [comment]
Thanks for your report. The SQL provided by you is very helpful. I can reproduce the problem easily.

I've fixed it.

**Comment by kitora** [comment]
Thank you for your rapid fix. I will check when you release next version.

**Comment by kitora** [comment]
I checked mroonga7.00 on centos:centos5.8 docker instance, but unfortunately this issue remains.
Any special settings are needed?
